In [9]:
import pandas as pd
import numpy as np
import requests
import os
from datetime import datetime
print("Libraries imported successfully!")

Libraries imported successfully!

In [10]:
# Create a folder to store raw data
os.makedirs('data/raw', exist_ok=True)

# Base URL of CitiBike 2022 data
base_url = 'https://s3.amazonaws.com/tripdata/'

# List of 2022 CSV filenames (monthly)
files = [
    "202201-citibike-tripdata.csv",
    "202202-citibike-tripdata.csv",
    "202203-citibike-tripdata.csv",
    "202204-citibike-tripdata.csv",
    "202205-citibike-tripdata.csv",
    "202206-citibike-tripdata.csv",
    "202207-citibike-tripdata.csv",
    "202208-citibike-tripdata.csv",
    "202209-citibike-tripdata.csv",
    "202210-citibike-tripdata.csv",
    "202211-citibike-tripdata.csv",
    "202212-citibike-tripdata.csv"
]

# Download each file if not already downloaded
for file in files:
    file_path = os.path.join('data/raw', file)
    if not os.path.exists(file_path):
        print(f"Downloading {file}...")
        r = requests.get(base_url + file)
        with open(file_path, 'wb') as f:
            f.write(r.content)
    else:
        print(f"{file} already exists.")

Downloading 202201-citibike-tripdata.csv...
Downloading 202202-citibike-tripdata.csv...
Downloading 202203-citibike-tripdata.csv...
Downloading 202204-citibike-tripdata.csv...
Downloading 202205-citibike-tripdata.csv...
Downloading 202206-citibike-tripdata.csv...
Downloading 202207-citibike-tripdata.csv...
Downloading 202208-citibike-tripdata.csv...
Downloading 202209-citibike-tripdata.csv...
Downloading 202210-citibike-tripdata.csv...
Downloading 202211-citibike-tripdata.csv...
Downloading 202212-citibike-tripdata.csv...

In [11]:
# Notebook cell: list CSV files in current folder
import os, glob, pathlib
cwd = pathlib.Path.cwd()
print("Current working directory:", cwd)
csvs = list(cwd.glob("../data/raw/*.csv"))
print(f"Found {len(csvs)} csv file(s) in this folder:")
for f in csvs:
    print(" -", f.name)
# also print top-level filenames for quick glance
print("\nTop-level items:")
for p in cwd.iterdir():
    print(" ", p.name)

Current working directory: /Users/karen/Desktop/CF/citi-bike-nyc-2022-dashboard/notebooks
Found 12 csv file(s) in this folder:
 - JC-202203-citibike-tripdata.csv
 - JC-202201-citibike-tripdata.csv
 - JC-202209-citibike-tripdata.csv
 - JC-202211-citibike-tripdata.csv
 - JC-202207-citbike-tripdata.csv
 - JC-202205-citibike-tripdata.csv
 - JC-202202-citibike-tripdata.csv
 - JC-202208-citibike-tripdata.csv
 - JC-202206-citibike-tripdata.csv
 - JC-202210-citibike-tripdata.csv
 - JC-202204-citibike-tripdata.csv
 - JC-202212-citibike-tripdata.csv

Top-level items:
  citi_dashboard_Part_2.py
  citi_dashboard.py
  2.2_citibike_weather_merge.ipynb
  Configurations.ipynb
  2.6_Creating Dashboards with Python.ipynb
  2.4_fundamentals_of_visualization_libraries_part_2.ipynb
  2.5_advanced_geospatial_plotting.ipynb
  data
  2.3_fundamentals_of_visualization_libraries_Part 1.ipynb

In [12]:
# Read and combine all monthly CSVs
all_data = []

for file in csvs:
    df = pd.read_csv(os.path.join('data/raw', file))
    all_data.append(df)

# Combine into a single DataFrame
citi_bike_df = pd.concat(all_data, ignore_index=True)

# Check the first few rows
citi_bike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member

In [17]:
citi_bike_df['date'] = pd.to_datetime(citi_bike_df['started_at']).dt.date
citi_bike_df.to_csv("../data/processed/citibike_2022.csv",index=False)
citi_bike_df.shape

(895485, 14)

In [23]:
from calendar import monthrange

token = "BrcnJvKuLUNfaNeeASmxwIOIhHHJhWyW"
url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
headers = {"token": token}

In [24]:
all_results = []

for month in range(1, 13):
    startdate = f"2022-{month:02d}-01"
    last_day = monthrange(2022, month)[1]
    enddate = f"2022-{month:02d}-{last_day}"

    params = {
        "datasetid": "GHCND",
        "stationid": "GHCND:USW00014732",  # LaGuardia
        "datatypeid": "TAVG",
        "startdate": startdate,
        "enddate": enddate,
        "units": "metric",
        "limit": 1000
    }

    r = requests.get(url, headers=headers, params=params)
    r.raise_for_status()

    data = r.json().get("results", [])
    all_results.extend(data)

In [ ]:
# Concatenate into DataFrame
weather_data = pd.DataFrame(all_results)

# Parse date
weather_data["date"] = pd.to_datetime(weather_data["date"])

# Keep only needed columns
weather_data = weather_data[["date", "value"]].rename(columns={"value": "avgTemp"})

# Sort for sanity
weather_data = weather_data.sort_values("date").reset_index(drop=True)

        date  avgTemp
0 2022-01-01     11.6
1 2022-01-02     11.4
2 2022-01-03      1.4
3 2022-01-04     -2.7
4 2022-01-05      3.2

In [27]:
weather_data.head()

        date  avgTemp
0 2022-01-01     11.6
1 2022-01-02     11.4
2 2022-01-03      1.4
3 2022-01-04     -2.7
4 2022-01-05      3.2

In [28]:
weather_data.tail()

          date  avgTemp
360 2022-12-27     -0.7
361 2022-12-28      3.4
362 2022-12-29      6.4
363 2022-12-30      9.3
364 2022-12-31      8.2

In [30]:

# Save to CSV
os.makedirs('data/processed', exist_ok=True)
weather_data.to_csv('../data/processed/la_guardia_weather_2022.csv', index=False)

In [14]:
#! Attention -- Load and inspect the saved weather data
weather_df = pd.read_csv('../data/processed/la_guardia_weather_2022.csv', parse_dates=['date'])
print(weather_df.shape)
weather_df.head()

(365, 2)

        date  avgTemp
0 2022-01-01     11.6
1 2022-01-02     11.4
2 2022-01-03      1.4
3 2022-01-04     -2.7
4 2022-01-05      3.2

In [19]:
#! Attention -- Load and inspect the saved weather data

citi_bike_df = pd.read_csv('../data/processed/citibike_2022.csv',parse_dates=['date'])
print(citi_bike_df.shape)
citi_bike_df.head()

(895485, 14)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual,2022-03-18
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-04
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-11

In [20]:
# Merge on date
merged_df = pd.merge(citi_bike_df, weather_df, on='date', how='left')

# Save merged CSV
merged_df.to_csv('../data/processed/citi_bike_with_weather_2022.csv', index=False)
merged_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,avgTemp
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual,2022-03-18,13.9
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-04,-1.9
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,-2.3
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,-2.3
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-11,7.2

**Data sources**
- CitiBike trip data (2022) — raw CSV files per month/period (downloaded from S3).
- NOAA daily weather (LaGuardia station) — daily average temperature for 2022 (obtained via NOAA API).

**What\s the Task Here**
- Combined all CitiBike 2022 CSVs into a single DataFrame using a memory-efficient pattern:  
  `pd.concat((pd.read_csv(f) for f in filepaths), ignore_index=True)`.
- Retrieved daily avg temperature (TAVG) for LaGuardia via NOAA API, converted values from tenths of °C to °C.
- Created `date` columns in both datasets (CitiBike: from `start_time`; NOAA: parsed datetimes), and merged by `date` using a left join:
  `df_merged = df.merge(df_temps, how='left', on='date', indicator=True)`.
- Saved a merged CSV locally: `data/processed/citibike_nyc_2022_with_weather.csv`.

**Relationship & what achieved**
- The merged dataset attaches daily weather (avg temperature) to each bike trip, enabling analysis of how temperature correlates with ridership (seasonality, peaks).
- With this merged data we can now create strategic visualizations: top stations (bar charts), monthly trips vs temperature (line charts), and geospatial route analysis (maps). This completes the data-prep stage; next step is to build interactive visuals/dashboards.

**Notes**
- Large raw / processed data files are excluded from the Git repo (`.gitignore` includes `data/`) to respect GitHub size limits. The notebooks and sample outputs are included in the repository.