In [3]:
# Notebook Cell 1: imports & path
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pathlib import Path
import matplotlib.pyplot as plt
from datetime import datetime as dt

MERGED_CSV =  "../data/processed/citi_bike_with_weather_2022.csv"

print("Using MERGED_CSV:", MERGED_CSV)

Using MERGED_CSV: ../data/processed/citi_bike_with_weather_2022.csv

In [4]:

df = pd.read_csv(MERGED_CSV, low_memory=False, parse_dates=['started_at', 'ended_at', 'date'])
print("Loaded df shape:", df.shape)
display(df.head())

Loaded df shape: (895485, 15)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,avgTemp
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual,2022-03-18,NaN
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-04,NaN
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,NaN
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,NaN
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-11,NaN

In [5]:
print(df.dtypes)
display(df.head(3))

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
date                  datetime64[ns]
avgTemp                      float64
dtype: object

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,avgTemp
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual,2022-03-18,NaN
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-04,NaN
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member,2022-03-13,NaN

In [ ]:
# set counter
df['trip_count'] = 1

In [8]:
df['trip_count'] = 1

daily = df.groupby('date').agg(
    trips=('bike_rides_daily','sum'),
    avg_temp=('avgTemp','mean')
).reset_index()

daily.head()

        date  trips  avg_temp
0 2022-01-01    592      11.6
1 2022-01-02   1248      11.4
2 2022-01-03    832       1.4
3 2022-01-04    934      -2.7
4 2022-01-05    914       3.2

In [10]:
# D1: Top 20 start stations and Plotly bar
import plotly.graph_objects as go
from pathlib import Path

station_counts = df.groupby('start_station_name').agg(count=('trip_count','sum')).reset_index()
top20 = station_counts.nlargest(20, 'count').reset_index(drop=True)

# plot horizontal bar (readable station names)
fig_bar = go.Figure(go.Bar(
    x=top20['count'][::-1],
    y=top20['start_station_name'][::-1],
    orientation='h',
    marker=dict(color=top20['count'], colorscale='Blues')
))
fig_bar.update_layout(title='Top 20 Start Stations', xaxis_title='Trips', height=700, margin=dict(l=300))
fig_bar.show()

# save top20 csv for Streamlit
out =  "../data/processed/top20.csv"
top20.to_csv(out, index=False)
print("Saved top20 to:", out)

Saved top20 to: ../data/processed/top20.csv

In [12]:
daily.head()

        date  trips  avg_temp
0 2022-01-01    592      11.6
1 2022-01-02   1248      11.4
2 2022-01-03    832       1.4
3 2022-01-04    934      -2.7
4 2022-01-05    914       3.2

In [13]:
# E1: Dual-axis chart using daily_df
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# ensure date is datetime
daily['date'] = pd.to_datetime(daily['date'])

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=daily['date'], y=daily['trips'],
                         name='Daily Bike Rides', mode='lines'), secondary_y=False)

fig.add_trace(go.Scatter(x=daily['date'], y=daily['avg_temp'],
                             name='Avg Temp', mode='lines'), secondary_y=True)

fig.update_yaxes(title_text="Bike rides (count)", secondary_y=False)
fig.update_yaxes(title_text="Temperature", secondary_y=True)
fig.update_layout(title='Daily Bike Rides and Temperature', height=600)
fig.show()

### How the plotting code works
1. I parsed `started_at` into datetime and created a `date` column to be able to aggregate daily counts.
2. I used pandas `groupby()` to compute `bike_rides_daily`.
3. For plotting I used Plotly:
   - Top20 bar chart: `go.Bar` with horizontal orientation for readability.
   - Dual-axis time series: `make_subplots(specs=[[{"secondary_y": True}]])` and `fig.add_trace()` for bike rides and temperature.
4. This approach is "axes-level" (explicit figure/axes/traces) similar to matplotlib's object-oriented pattern — it gives us full control and interactivity.